<?php $this->inlineScript()->appendFile('/js/markdown.js') ?>
<?php $this->inlineScript()->captureStart(); ?>
    var writer = $('.markdown-writer');
    var container = $('.markdown-container');
    container.html(markdown.toHTML(writer.val()));
    writer.on('keyup', function() {
        container.html(markdown.toHTML(writer.val()));
    });
<?php $this->inlineScript()->captureEnd(); ?>
<h3>Add Blog</h3>
<div class="row">
    <div class="col-md-6">
        <?= $this->form($this->form) ?>
    </div>
    <div class="col-md-6">
        <div class="markdown-container">

        </div>
    </div>
</div>
