<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('tl;dev')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?php echo $this->headLink()
                    ->prependStylesheet($this->basePath() . '/css/style.css')
                    ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
</head>
<body>
    <div class="wrapper">
        <div class="navbar navbar-default thelazyblue">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?= $this->url('index', array('uri' => 'index.'.$this->randomExtension())) ?>">tl;dev</a>
            </div>
            <div class="navbar-collapse collapse navbar-responsive-collapse">
                <ul class="nav navbar-nav">

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="https://github.com/tldev" target="_blank">github</a></li>
                    <li><a href="<?= $this->url('about', array('uri' => 'about.'.$this->randomExtension())) ?>">about</a></li>
                </ul>
            </div>
        </div>
        <?= $this->flashMessenger()->render('info') ?>
        <div class="container">
            <?php echo $this->content; ?>
        </div>
        <div class="push"></div>
    </div>
    <div class="footer">
        <div class="container">
            <footer>
                <hr>
                <p>
                    <a href="<?= $this->url('lazy', array('uri' => 'lazy.'.$this->randomExtension())) ?>">&copy; <?php echo date('Y') ?> <?= $this->author() ?></a>
                    <small><a href="https://github.com/tldev/tldev" target="_blank">tldev/tldev</a></small>
                </p>
            </footer>
        </div>
    </div>
    <?php echo $this->inlineScript()
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-51501365-1', 'thelazydeveloper.com');
        ga('send', 'pageview');

    </script>
</body>
</html>
