<div class="row">
    <h2>About Me <small>Tom Johnell</small></h2>
    <hr>
    <p>
        <h3>Fun</h3>
        Music, video games, beer, books, programming, lifting.
    </p>
    <p>
        <h3>Work</h3>
        I've been a PHP developer for over <?= $this->years ?> years now.  I took a few programming courses in college,
        but all of my practical knowledge has come from getting my hands dirty on the job.
    </p>
</div>