<div class="jumbotron hidden-xs">
    <h1 class="longword">thelazydeveloper</h1>
    <p>A home for the ramblings of <?= $this->author(); ?></p>
</div>
<div class="minitron visible-xs">
    <h3>thelazydeveloper</h3>
    <small>A home for the ramblings of <?= $this->author(); ?></small>
</div>
<hr>
<h3>Recent Activity</h3>
<ul>
    <li>
        <a href="http://www.booj.com/blog/its-hard-to-mess-up-vagrant-up" target="_blank">It's Hard To Mess Up Vagrant Up</a>
    </li>
    <li>
        <a href="<?= $this->url('markers') ?>">Numbered Google Map Markers</a>
    </li>
</ul>

