<?php $this->headLink()->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/octicons/2.0.2/octicons.min.css') ?>
<?php $this->headLink()->appendStylesheet('//caseyscarborough.github.io/github-activity/github-activity-0.1.0.min.css') ?>
<?php $this->inlineScript()->appendFile('//cdnjs.cloudflare.com/ajax/libs/mustache.js/0.7.2/mustache.min.js') ?>
<?php $this->inlineScript()->appendFile($this->basePath() . 'js/github-activity.min.js') ?>
<?php $this->inlineScript()->captureStart(); ?>
GitHubActivity.feed({ username: "tldev", selector: "#github-feed", limit:5 });
<?php $this->inlineScript()->captureEnd(); ?>
<div id="pg-me" class="container text-center">
        <div class="hero-unit">
            Hello.
        </div>
        <h1>I'm Thomas Johnell.</h1>
        <p>
            When I'm not building web applications, I'm watching football and contributing to open-source.
        </p>
</div>
<div id="main-images" class="container">
    <div class="col-lg-4">
        <img class="img-responsive center-block" src="img/pic-bronco.png" />
    </div>
    <div class="col-lg-4">
        <img class="img-responsive center-block" src="img/pic-guitar.png" />
    </div>
    <div class="col-lg-4">
        <img class="img-responsive center-block" src="img/pic-team.png" />
    </div>
</div>
<div id="pg-capabilities">
    <div class="container text-center">
        <h1>My capabilities.</h1>
        <p>PHP</p>
        <p>MySQL</p>
        <p>OOP</p>
        <p>Javacript</p>
        <p>SVN/Git</p>
        <button type="button" class="btn btn-lg">
            <a href="#">
                download resume
            </a>
        </button>
    </div>
</div>
<div id="pg-github">
    <div class="container">
        <div id="github-feed" style="position: relative"></div>
    </div>
</div>
