<?php $this->headLink()->appendStylesheet('css/github-activity.min.css') ?>
<?php $this->inlineScript()->appendFile($this->basePath() . 'js/mustache.min.js') ?>
<?php $this->inlineScript()->appendFile($this->basePath() . 'js/github-activity.min.js') ?>
<?php $this->inlineScript()->appendFile($this->basePath() . 'js/swipe.min.js') ?>
<?php
$js = <<<JS
    GitHubActivity.feed({
        username: "tldev",
        selector: "#github-feed",
        limit:5,
        templates: {
            Footer: '',
            SingleLineActivity: '<div id="{{id}}" class="gha-activity">\
               <div class="gha-activity-icon"><span class="octicon octicon-{{icon}}"></span></div>\
               <div class="gha-message"><div class="gha-time">{{{timeString}}}</div>{{{userLink}}} {{{message}}}</div>\
               <div class="gha-clear"></div>\
             </div>'
        }
    });

    Swipe(document.getElementById('mobile-slider'), {auto:5000});

    $("#resume-button").on('click', function(e) {
        e.preventDefault();
        $("#resume-options").toggle();
    });
JS;
$this->inlineScript()->appendScript($js)
?>
<div id="pg-me" class="container text-center">
    <div class="hero-unit">
        Hello.
    </div>
    <div>
        <img class="usb" src="img/usb-black.png" />
    </div>
    <h1>I'm Thomas Johnell.</h1>
    <p>
        When I'm not busy building web applications, I'm watching football and contributing to open-source.
    </p>
</div>
<div id="main-images" class="container hidden-xs hidden-sm hidden-md">
    <div class="col-lg-4">
        <img class="img-responsive center-block" src="img/pic-broncos.jpg" />
    </div>
    <div class="col-lg-4">
        <img class="img-responsive center-block" src="img/pic-guitar.jpg" />
    </div>
    <div class="col-lg-4">
        <img class="img-responsive center-block" src="img/pic-team.jpg" />
    </div>
</div>
<div id="mobile-images" class="container visible-xs visible-sm visible-md">
    <div id="mobile-slider" class="swipe" >
        <div class="swipe-wrap">
            <div>
                <img class="img-responsive center-block" src="img/pic-broncos.jpg">
            </div>
            <div>
                <img class="img-responsive center-block" src="img/pic-guitar.jpg">
            </div>
            <div>
                <img class="img-responsive center-block" src="img/pic-team.jpg">
            </div>
        </div>
    </div>
</div>
<div id="pg-capabilities">
    <div class="container text-center">
        <h1>My capabilities.</h1>
        <p>PHP</p>
        <p>MySQL</p>
        <p>Object-Oriented Programming</p>
        <p>Javascript</p>
        <p>SVN/Git</p>
        <div>
            <img class="usb" src="img/usb-white.png" />
        </div>
        <button id="resume-button" type="button" class="btn btn-lg">
            <a href="#">
                download resume
            </a>
        </button>
        <div id="resume-options" style="display:none;">
            <button type="button" class="btn btn-lg">
                <a href="<?= $this->url('download', array('filename' => 'ThomasJohnellResume', 'ext' => 'pdf')); ?>">
                    pdf
                </a>
            </button>
            <button type="button" class="btn btn-lg">
                <a href="<?= $this->url('download', array('filename' => 'ThomasJohnellResume', 'ext' => 'docx')); ?>">
                    docx
                </a>
            </button>
            <button type="button" class="btn btn-lg">
                <a href="<?= $this->url('download', array('filename' => 'ThomasJohnellResume', 'ext' => 'txt')); ?>">
                    txt
                </a>
            </button>
        </div>
    </div>
</div>
<div id="pg-github">
    <div class="container">
        <div id="github-feed" style="position: relative"></div>
    </div>
    <div class="container text-center">
        <button type="button" class="btn btn-lg">
            <a target="_blank" href="https://github.com/tldev">
                my github
            </a>
        </button>
    </div>
</div>
