<h3>Laziness</h3>
<p>
<blockquote>
    <p>
        The quality that makes you go to great effort to reduce overall energy expenditure.
        It makes you write labor-saving programs that other people will find useful,
        and document what you wrote so you don't have to answer so many questions about it.
        Hence, the first great virtue of a programmer.
        <footer>
            Larry Wall in <cite title="Programming Perl (1st Edition)">Programming Perl (1st Edition)</cite>
        </footer>
    </p>
</blockquote>
</p>