<div class="container resume">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-sm-push-6">
            <div class="download-options pull-right-sm">
                <a href="<?= $this->url('download', array('filename' => 'ThomasJohnellResume', 'ext' => 'pdf')); ?>">
                    pdf
                </a>
                <a href="<?= $this->url('download', array('filename' => 'ThomasJohnellResume', 'ext' => 'docx')); ?>">
                    docx
                </a>
                <a href="<?= $this->url('download', array('filename' => 'ThomasJohnellResume', 'ext' => 'txt')); ?>">
                    txt
                </a>
            </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-sm-pull-6">
            <h1 class="title">Thomas Johnell</h1>
            <h2>PHP Web Developer</h2>
            <h3>
                <a href="tel:+19703018856">970-301-8856</a> <span>|</span> <a href="mailto:tjohnell@gmail.com">tjohnell@gmail.com</a>
            </h3>
        </div>
    </div>
    <!-- Experience !-->
    <div class="row">
        <div class="col-xs-12 col-lg-6">
            <h3 class="subtitle">EXPERIENCE</h3>
            <h2>
                1bg, formerly booj
            </h2>
            <span class="years">2013 - present</span>
            <h3 style="margin-top: 0;">Senior Web Developer</h3>
            <ul>
                <li>
                    Planned and developed extensible system similar to DocuSign, utilizing OO design, caching, PDF
                    rasterization with Imagick, and event listening via Zend Framework EventManager.
                </li>
                <li>Successfully forked a six year old Zend Framework application for the purpose of rebranding,
                    requiring extensive data migrations in MySQL.
                </li>
                <li>
                    Integrated Composer into legacy application to allow for the utilization of open source libraries
                    such as DoctrineORM and Flysystem.
                </li>
                <li>
                    Built an OO library to allow for seamless integration with MailChimp’s API to track email
                    subscribers
                </li>
            </ul>
            <span class="years">2012-2013</span>
            <h3>Intermediate Web Developer</h3>
            <ul>
                <li>
                    Wrote a MySQL database driven form builder with input templates, validation, and filtering.
                </li>
                <li>
                    Re-wrote classic ASP library for receiving a json payload and writing to PDF form fields using
                    AspPDF.
                </li>
            </ul>
            <span class="years">2011-2012</span>
            <h3>Junior Web Developer</h3>
            <ul>
                <li>
                    Assisted in the development of an internal tool for communicating with the Twilio via API to track
                    and send text messages, text blasts, and phone calls
                </li>
                <li>
                    Created marketing pages with HTML, CSS, and Javascript.
                </li>
            </ul>
        </div>
    </div>
    <!-- Education !-->
    <div class="row">
        <div class="col-xs-12">
            <h3 class="subtitle">EDUCATION</h3>
            <h2>University of Northern Colorado</h2>
            <h3>Bachelor of Science in Mathematics</h3>
            <span>Summa Cum Laude, Dean’s List</span>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <h3 class="subtitle">SKILLS</h3>
            <ul>
                <li>Linux, Apache, MySQL, PHP (4 years)</li>
                <li>Object-Oriented Programming (4 years)</li>
                <li>Git/Subversion (4 years)</li>
                <li>Javascript (4 years)</li>
                <li>MVC (4 years)</li>
                <li>System Administration (3 years)</li>
                <li>Code Review (2 years)</li>
                <li>Unit-testing (1 year)</li>
            </ul>
        </div>
    </div>
</div>

