<div class="container resume">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-sm-push-6">
            <div id="resume-options" class="pull-right-sm">
                <button type="button" class="btn btn-lg button-block-xs">
                    <a href="<?= $this->url('download', array('filename' => 'ThomasJohnellResume', 'ext' => 'pdf')); ?>">
                        pdf
                    </a>
                </button>
                <button type="button" class="btn btn-lg button-block-xs">
                    <a href="<?= $this->url('download', array('filename' => 'ThomasJohnellResume', 'ext' => 'docx')); ?>">
                        docx
                    </a>
                </button>
                <button type="button" class="btn btn-lg button-block-xs">
                    <a href="<?= $this->url('download', array('filename' => 'ThomasJohnellResume', 'ext' => 'txt')); ?>">
                        txt
                    </a>
                </button>
            </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-sm-pull-6">
            <h1 class="title">Thomas Johnell</h1>
            <h2>PHP Web Developer</h2>
            <h3>
                <a href="tel:+19703018856">970-301-8856</a> <span>|</span> <a href="mailto:tjohnell@gmail.com">tjohnell@gmail.com</a>
            </h3>
        </div>
    </div>
    <!-- Experience !-->
    <div class="row">
        <div class="col-xs-12">
            <h3 class="subtitle">EXPERIENCE</h3>
            <h2>
                1bg, formerly booj
            </h2>
            <span class="years">2013 - present</span>
            <h3 style="margin-top: 0;">Lead Web Developer</h3>
            <ul>
                <li>Lead a team of four junior to intermediate web developers</li>
                <li>Plan, develop, and delegate long-term projects</li>
                <li>Organize and execute weekly deployment process</li>
                <li>Code review and enforce standards</li>
            </ul>
            <span class="years">2012-2013</span>
            <h3>Intermediate Web Developer</h3>
            <ul>
                <li>Planned and developed long-term feature requests and site improvements</li>
                <li>Developed WM related marketing pages with HTML/CSS</li>
            </ul>
            <span class="years">2011-2012</span>
            <h3>Junior Web Developer</h3>
            <ul>
                <li>Collaborated and developed in LAMP stack environment</li>
                <li>Provided quality assurance on outgoing tickets</li>
            </ul>
        </div>
    </div>
    <!-- Education !-->
    <div class="row">
        <div class="col-xs-12">
            <h3 class="subtitle">EDUCATION</h3>
            <h2>University of Northern Colorado</h2>
            <h3>Bachelor of Science in Mathematics</h3>
            <span>Summa Cum Laude, Dean’s List</span>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <h3 class="subtitle">SKILLS</h3>
            <ul>
                <li>Linux, Apache, MySQL, PHP</li>
                <li>Object-Oriented Programming</li>
                <li>Git/Subversion</li>
                <li>Unit-testing</li>
                <li>Javascript</li>
            </ul>
        </div>
    </div>
</div>

